openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/auth/register:
    post:
      summary: ''
      operationId: postApiV1AuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: 'First Name. Must be at least 2 characters. Must not be greater than 255 characters.'
                  example: John
                last_name:
                  type: string
                  description: 'Last Name. Must be at least 2 characters. Must not be greater than 255 characters.'
                  example: Doe
                email:
                  type: string
                  description: 'Email. Must be a valid email address.'
                  example: john@doe
                password:
                  type: string
                  description: Password.
                  example: yqy5bjd7vkg@ckm5THG
                password_confirmation:
                  type: string
                  description: 'Confirmation Password.'
                  example: yqy5bjd7vkg@ckm5THG
              required:
                - first_name
                - last_name
                - email
                - password
                - password_confirmation
      security: []
  /api/v1/auth/login:
    post:
      summary: ''
      operationId: postApiV1AuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Email. Must be a valid email address.'
                  example: john@doe
                password:
                  type: string
                  description: Password.
                  example: yqy5bjd7vkg@ckm5THG
              required:
                - email
                - password
      security: []
  /api/v1/ping:
    get:
      summary: ''
      operationId: getApiV1Ping
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Pong
                properties:
                  message:
                    type: string
                    example: Pong
      tags:
        - Healthcheck
      security: []
  /api/v1/users:
    get:
      summary: ''
      operationId: getApiV1Users
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 18
                    uuid: d3e1995b-f712-4606-a365-8b564157f22d
                    first_name: Declan
                    last_name: Wolf
                    email: morissette.jaylen@example.org
                    email_verified_at: '2024-01-09T20:25:31.000000Z'
                    created_at: '2024-01-09T20:25:31.000000Z'
                    updated_at: '2024-01-09T20:25:31.000000Z'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 18
                      uuid:
                        type: string
                        example: d3e1995b-f712-4606-a365-8b564157f22d
                      first_name:
                        type: string
                        example: Declan
                      last_name:
                        type: string
                        example: Wolf
                      email:
                        type: string
                        example: morissette.jaylen@example.org
                      email_verified_at:
                        type: string
                        example: '2024-01-09T20:25:31.000000Z'
                      created_at:
                        type: string
                        example: '2024-01-09T20:25:31.000000Z'
                      updated_at:
                        type: string
                        example: '2024-01-09T20:25:31.000000Z'
      tags:
        - Users
  '/api/v1/users/{uuid}':
    get:
      summary: ''
      operationId: getApiV1UsersUuid
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Users
    delete:
      summary: ''
      operationId: deleteApiV1UsersUuid
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Users
    parameters:
      -
        in: path
        name: uuid
        description: ''
        example: 80c4d732-1106-3c34-9295-69c31b06ae90
        required: true
        schema:
          type: integer
tags:
  -
    name: Auth
    description: ''
  -
    name: Healthcheck
    description: ''
  -
    name: Users
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
