openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/auth/register:
    post:
      summary: ''
      operationId: postApiV1AuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: 'First Name. Must be at least 2 characters. Must not be greater than 255 characters.'
                  example: John
                last_name:
                  type: string
                  description: 'Last Name. Must be at least 2 characters. Must not be greater than 255 characters.'
                  example: Doe
                email:
                  type: string
                  description: 'Email. Must be a valid email address.'
                  example: john@doe
                password:
                  type: string
                  description: Password.
                  example: yqy5bjd7vkg@ckm5THG
                password_confirmation:
                  type: string
                  description: 'Confirmation Password.'
                  example: yqy5bjd7vkg@ckm5THG
              required:
                - first_name
                - last_name
                - email
                - password
                - password_confirmation
      security: []
  /api/v1/auth/login:
    post:
      summary: ''
      operationId: postApiV1AuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Email. Must be a valid email address.'
                  example: john@doe
                password:
                  type: string
                  description: Password.
                  example: yqy5bjd7vkg@ckm5THG
              required:
                - email
                - password
      security: []
  /api/v1/ping:
    get:
      summary: ''
      operationId: getApiV1Ping
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Pong
                properties:
                  message:
                    type: string
                    example: Pong
      tags:
        - Healthcheck
      security: []
tags:
  -
    name: Auth
    description: ''
  -
    name: Healthcheck
    description: ''
